from __future__ import annotations

from typing import Annotated

from pydantic import Field

from gremlin_mcp.pipeline import SPECIALISTS
from gremlin_mcp.research_executor import MAX_RESEARCH_SOURCES
from gremlin_mcp.router import MAX_ROUTE_SPECIES
from gremlin_mcp.web import (
    MAX_LIMIT,
    MAX_RESPONSE_BYTES,
    MAX_TIMEOUT_S,
    MIN_RESPONSE_BYTES,
    MIN_TIMEOUT_S,
)
from gremlin_mcp.workers import (
    MAX_IDENTIFIER_CHARS,
    MAX_LEASE_SECONDS,
    MAX_WORKER_BATCH,
    MAX_WORKER_VECTOR_WIDTH,
)

if MAX_ROUTE_SPECIES != len(SPECIALISTS):
    raise RuntimeError("MAX_ROUTE_SPECIES drifted from SPECIALISTS")


RouteMaxSpecies = Annotated[
    int,
    Field(
        ge=1,
        le=MAX_ROUTE_SPECIES,
        description="Maximum OCTOPUS specialist roles selected for one route.",
    ),
]

RouteMinScore = Annotated[
    float,
    Field(
        gt=0.0,
        description="Positive absolute OCTOPUS evidence-score floor.",
    ),
]

RouteRelativeCutoff = Annotated[
    float,
    Field(
        gt=0.0,
        le=1.0,
        description="Relative OCTOPUS cutoff as a fraction of the top route score.",
    ),
]

ProviderLimit = Annotated[
    int,
    Field(
        ge=1,
        le=MAX_LIMIT,
        description="Maximum candidate results requested from each public research provider.",
    ),
]

ResearchMaxSources = Annotated[
    int,
    Field(
        ge=1,
        le=MAX_RESEARCH_SOURCES,
        description="Maximum deduplicated evidence sources admitted to staged research execution.",
    ),
]

WebTimeoutSeconds = Annotated[
    float,
    Field(
        ge=MIN_TIMEOUT_S,
        le=MAX_TIMEOUT_S,
        description="Bounded HTTPS request timeout in seconds.",
    ),
]

WebMaxBytes = Annotated[
    int,
    Field(
        ge=MIN_RESPONSE_BYTES,
        le=MAX_RESPONSE_BYTES,
        description="Maximum raw HTTPS response bytes accepted before fail-closed rejection.",
    ),
]

PlanVectorWidth = Annotated[
    int,
    Field(
        ge=1,
        description="Positive vector lane width used by the deterministic Bestiary plan.",
    ),
]

NonNegativeRouteCount = Annotated[
    int,
    Field(
        ge=0,
        description="Non-negative routed work count for one scheduler-backed species.",
    ),
]

NonEmptyStringList = Annotated[
    list[str],
    Field(
        min_length=1,
        description="Non-empty list required by the corresponding GREMLIN runtime contract.",
    ),
]

RequestId = Annotated[
    str,
    Field(
        min_length=1,
        max_length=64,
        description="Optional caller correlation ID; generated by GREMLIN when omitted.",
    ),
]

WorkerIdentifier = Annotated[
    str,
    Field(
        min_length=1,
        max_length=MAX_IDENTIFIER_CHARS,
        description="GREMLIN worker/task/lease identifier.",
    ),
]

WorkerIdentifierList = Annotated[
    list[WorkerIdentifier],
    Field(
        min_length=1,
        description="Non-empty list of GREMLIN task identifiers.",
    ),
]

WorkerVectorWidth = Annotated[
    int,
    Field(
        ge=1,
        le=MAX_WORKER_VECTOR_WIDTH,
        description="External worker vector width admitted by the worker ABI.",
    ),
]

WorkerMaxBatch = Annotated[
    int,
    Field(
        ge=1,
        le=MAX_WORKER_BATCH,
        description="Maximum same-species task batch accepted for one external worker.",
    ),
]

WorkerClaimLimit = Annotated[
    int,
    Field(
        ge=1,
        description="Positive requested claim size; runtime additionally caps it by worker and geometry limits.",
    ),
]

WorkerLeaseSeconds = Annotated[
    int,
    Field(
        ge=1,
        le=MAX_LEASE_SECONDS,
        description="Requested task lease lifetime in seconds.",
    ),
]
